# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Jobs to add file in the workspace and read them
jobs:
  # JOB to create output.txt file and save it in the workspace
  add_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
     - run: echo "Hello World" > ~/output.txt
     - persist_to_workspace:
        root: ~/
        paths:
          - output.txt 
  
workflows:
  # Name the workflow "welcome"
  my_workflow:
    # Run the jobs listed above
    jobs:
      - add_file
